#!/bin/bash
INPUT_POSITION=$1

function fib {
  FIB_POSITION_WANTED=$1
  echo "DEBUG: Calculate Fib Position = $FIB_POSITION_WANTED"
  FIB_NUMBER_1=0
  FIB_NUMBER_2=1
  CURRENT_POSITION=0

  while [ $CURRENT_POSITION -le $(($FIB_POSITION_WANTED - 1)) ]
  do
    let CURRENT_FIB=$FIB_NUMBER_1+$FIB_NUMBER_2
    let CURRENT_POSITION=$CURRENT_POSITION+1
    echo "DEBUG: curr=${CURRENT_FIB}(${CURRENT_POSITION}), 1=${FIB_NUMBER_1}, 2=${FIB_NUMBER_2}"
    FIB_NUMBER_1=$FIB_NUMBER_2
    FIB_NUMBER_2=$CURRENT_FIB
  done
  echo "fib number ${CURRENT_POSITION} is ${CURRENT_FIB}"
}

fib $INPUT_POSITION